spring.datasource.url=jdbc:mysql://localhost:3306/ekart
spring.datasource.username=root
spring.datasource.password=entc112107068

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.ekart.model
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

server.port=8081

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000